const types = {
  GET_COUNTRIES_REQUEST: "GET_COUNTRIES_REQUEST",
  GET_COUNTRIES_SUCCESS: "GET_COUNTRIES_SUCCESS",
  GET_COUNTRIES_FAILURE: "GET_COUNTRIES_FAILURE",

  GET_STATES_REQUEST: "GET_STATES_REQUEST",
  GET_STATES_SUCCESS: "GET_STATES_SUCCESS",
  GET_STATES_FAILURE: "GET_STATES_FAILURE",

  GET_GEODATA_REQUEST: "GET_GEODATA_REQUEST",
  GET_GEODATA_SUCCESS: "GET_GEODATA_SUCCESS",
  GET_GEODATA_FAILURE: "GET_GEODATA_FAILURE",

  GET_STATE_GEODATA_REQUEST: "GET_STATE_GEODATA_REQUEST",
  GET_STATE_GEODATA_SUCCESS: "GET_STATE_GEODATA_SUCCESS",
  GET_STATE_GEODATA_FAILURE: "GET_STATE_GEODATA_FAILURE",

  HANDLE_SELECT_COUNTRY: "HANDLE_SELECT_COUNTRY",
  HANDLE_SELECT_STATE: "HANDLE_SELECT_STATE",

};

export default types;
