const types = {
  GET_STATES_REQUEST: "GET_STATES_REQUEST",
  GET_STATES_SUCCESS: "GET_STATES_SUCCESS",
  GET_STATES_FAILURE: "GET_STATES_FAILURE",

  GET_CITIES_REQUEST: "GET_CITIES_REQUEST",
  GET_CITIES_SUCCESS: "GET_CITIES_SUCCESS",
  GET_CITIES_FAILURE: "GET_CITIES_FAILURE",

  GET_STATE_GEODATA_REQUEST: "GET_STATE_GEODATA_REQUEST",
  GET_STATE_GEODATA_SUCCESS: "GET_STATE_GEODATA_SUCCESS",
  GET_STATE_GEODATA_FAILURE: "GET_STATE_GEODATA_FAILURE",

  GET_CITY_GEODATA_REQUEST: "GET_CITY_GEODATA_REQUEST",
  GET_CITY_GEODATA_SUCCESS: "GET_CITY_GEODATA_SUCCESS",
  GET_CITY_GEODATA_FAILURE: "GET_CITY_GEODATA_FAILURE",

  GET_CITY_WEATHER_DATA_REQUEST: "GET_CITY_WEATHER_DATA_REQUEST",
  GET_CITY_WEATHER_DATA_SUCCESS: "GET_CITY_WEATHER_DATA_SUCCESS",
  GET_CITY_WEATHER_DATA_FAILURE: "GET_CITY_WEATHER_DATA_FAILURE",

  HANDLE_SELECT_STATE: "HANDLE_SELECT_STATE",
  HANDLE_SELECT_CITY: "HANDLE_SELECT_CITY",

  SET_BORDER_COLOR_BY_TEMP: "SET_BORDER_COLOR_BY_TEMP",
};

export default types;
